feat: adjust naming artifact
kubeopsskills/cloud-secret-resolvers pull request #19
Opened 2022-05-25 10:22 UTC by Sikiryl

Change Log
- adjust naming of artifact in makefile

2022-05-25 10:23 UTC, Sikiryl commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx AST – Scan Summary & Details** – [2b796d8e\-f962\-45fa\-b242\-431030e36138](https://ast.checkmarx.net/projects/e89ef3ef-62fe-407b-94de-351d4a8973c0/scans?id=2b796d8e-f962-45fa-b242-431030e36138&branch=develop)
### No New Or Fixed Issues Found

2022-05-25 11:24 UTC, dmakeroam requested changes

2022-05-25 11:24 UTC, dmakeroam commented on Makefile
> +	env GOOS=darwin $(GOARCH) go build  -o ./$(TARGET_PATH)/csr $(GOMODULE)
For MacOS, Linux, Arm, in the build process, CSR will be built parallel for those platforms and the binary will be conflict.

2022-06-01 15:30 UTC, dmakeroam commented
LGTM !

2022-06-01 15:33 UTC, merged